// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://alubiqmigbbvatytqiem.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFsdWJpcW1pZ2JidmF0eXRxaWVtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzczNzg3ODYsImV4cCI6MjA1Mjk1NDc4Nn0.cgCcYjCa-xDJKwd8iKfFGnJMST_VZMiLFKfBEeInlK4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);